# Generated by Django 4.2 on 2025-04-08 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(help_text='O CRM deve ter o formato XX/XXXXX (ex:12/23456).', max_length=8, validators=[django.core.validators.RegexValidator(message="O formato do CRM deve ser XX/XXXXX. Todos os X's são números", regex='^\\d{2}/\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('PEDIATRA', 'Pediatra'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('GINECOLOGISTA', 'Ginecologista'), ('CARDIOLOGISTA', 'Cardiologista'), ('CAR', 'Car')], max_length=50),
        ),
    ]
